### ISSUE TITLE
es6方式如何使用

### ISSUE THREAD

**Issue by dabingliannaonao** [lzwme/ajax-data-model#1]
我通过 npm install 安装了模块后， 在项目中使用的时候，比如在一个main.js文件里面写了 如下代码 ：
```
import adm from 'ajax-data-model';
const param = {
    data: {},
    url: '../package.json',
    cache: 'localStorage',
    fromCache: 'localStorage',
};
adm.get(param).then((result) => {
    console.log(result);
}, (err) => {
    console.log(err);
}) 
```
通过 babel转码 main.js 文件为 boundle.js文件， 然后在我的我一个 a.html文件引用boundle.js文件后，在服务器环境打开我的a.html文件，发现根本无法使用，直接 报错说 require is not defined来着，  但是我不用楼主的模块，直接写es6代码的时候，是可以正常运行的，所以我觉得我应该是哪里配置有问题了，但是我又不知道如何解决问题，能麻烦楼主说一下 es6环境下稍微详细点的用法么？谢谢了！

**Comment by renxia** [comment]
babel 只负责转码 es6 语法，对于模块化依赖你还需要选择一个方案。
babel 对于 import 的引用默认应该是使用 commonjs 方案的，所以会报你提到的错误。
